language: ruby
rvm:
- 2.0.0
before_script:
- bundle exec rake --trace db:migrate
script:
- bundle exec rake --trace
deploy:
  provider: heroku
  api_key:
    secure: iG/HT2xk9vXj7cSbvI+zw6kYUe8VL6eGvS9bmTJarDhxPR7Y6UxPQzzJEDW7U2Vlh5SvzO6Uo5JFLCqJpr1JZG0zh38tnoEb6sZJP5waXo1/RiWL+d3zB2a6bOmogekDKLzkY3SLUy2kxEmOGpqfKriVXj3bPjlUffHW+zyZObM=
  app: arcane-basin-8034
  on:
    repo: cdamiano/sample_app
notifications:
  email:
    recipients:
      secure: "RFzhbp2J9adOl7QytSkGG2PBSdWTyhinD69B7NlOTArVpZgAk+OUcDFhu4VuFROkVNi3uYY34EAi7rPxvlqvWw+ZNQNdjyPI1eHBmeNMTB3O4iVi+m4/kU8kcYBid5EZNHaHT3/b3mo8MJb/TIuRdmWL1fqk545lZ4wRpginiY0="
    on_success: always
