language: ruby
cache: bundler
rvm:
- 2.0.0
before_script:
- cp config/database.yml.test config/database.yml
- bundle exec rake --trace db:migrate
script:
- bundle exec rake --trace
deploy:
  provider: heroku
  api_key:
    secure: iG/HT2xk9vXj7cSbvI+zw6kYUe8VL6eGvS9bmTJarDhxPR7Y6UxPQzzJEDW7U2Vlh5SvzO6Uo5JFLCqJpr1JZG0zh38tnoEb6sZJP5waXo1/RiWL+d3zB2a6bOmogekDKLzkY3SLUy2kxEmOGpqfKriVXj3bPjlUffHW+zyZObM=
  run: "rake db:migrate"
  app:
    master: arcane-basin-8034
    production: stormy-castle-9177
  on:
    repo: cdamiano/sample_app
notifications:
  email:
    - secure: "YBPtV8uZ27e4gZMSADgxUu0V/9P4WsPtpmk/ajGoIO3774rOMA4fHwymETGONc9RW4p+13hcd1aG0M3ddW41ywlqMEmvhyCuihGss5GBIYZVPH0Fiq9Ny2VLfDlcnhgPscGy6/kNztqhk9kmpK7JG+Jd/AwwF39jf/zc3VCIhpI="
